defaults:
  - scope:
      path: "assets/images/slider"
    values:
      slider_image: true

  - scope:
      path: "assets/images/clients_img"
    values:
      client_img: true

  - scope:
      path: "assets/images/projects"
    values:
      projects_image: true

  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      comments: "true"

  - scope:
      type: "pages"
    values:
      layout: "page"


permalink: /blog/:title/
paginate: 9
paginate_path: "/blog/page:num/"

name: feliperego
title: Example Companey
email: example@gmail.com
phone: +8801856120120
address: 1230 Dhaka , Bangladesh
description: > # this means to ignore newlines until "baseurl:"
  description there
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
minimalist-nav: true
theme: bazingafr.github.io


webmaster_verifications: # seo
  google:
  bing:

google_analytics: #google analytics
google_ad_client: 

timezone: Dhaka/Bangladesh  # your timezone

logo: /assets/images/logo.png # logo url

author: jubayed # author name



#

tag_page_layout: tag_page
tag_page_dir: tag

tag_feed_layout: tag_feed
tag_feed_dir: tag

tag_permalink_style: pretty
ignored_tags: [tags,to,ignore]

tag_page_data:
  sitemap: false

#

jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

enabled: all
enabled:
  - categories
enabled:
  - year
  - month
  - tags    
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.

exclude:
#  - .gitignore
#  - README.md
   - Gemfile
   - Gemfile.lock
   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

enabled: all
enabled:
  - categories
enabled:
  - year
  - month
  - tags