# Site settings
title: Felipe Rego
email: fe_cr@hotmail.com
description: Data Science | Predictive Analytics | Machine Learning | Statistical Analysis | Data Visualisation
baseurl:  # the subpath of your site, e.g. /blog/
url: "https://bazingafr.github.io" # the base hostname & protocol for your site
twitter_username: feliperego
github_username:  feliperego

# Build settings
markdown: kramdown
